baseURL = "/"
languageCode = "en-us"
title = "Topwise Support Pty Ltd"
themesDir = "themes"
theme = "hugo-topwise"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/WebLogo.webp"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/WebLogo.webp"
    desktop_height = "90px"
    desktop_width = "360px"
    alt = "Topwise Support"

  [params.homepage_meta_tags]
    meta_description = "Empowering The People We Support To Help Create A Better Everyday Life"
    meta_og_title = "Topwise Support Coordination Melbourne"
    meta_og_type = "website"
    meta_og_url = "https://www.topwisesupport.com.au/"
    meta_og_description = "Melbourne Based Support Cordination - Many Years of Knowledge for Your Betterment"
    meta_twitter_card = "summary"
    meta_og_image = "images/Weblinklogo.webp"

  [params.about_meta_tags]
    meta_description = "Our Focus is Prioritising The Rights and Preferences of The People We Support"
    meta_og_title = "About US - Topwise Support, Melbourne"
    meta_og_type = "website"
    meta_og_url = "https://www.topwisesupport.com.au/about/"
    meta_og_description = "Get to Know Topwise Support and Find Out How We Can Help"
    meta_twitter_card = "summary"
    meta_og_image = "images/Weblinklogo.webp"

  [params.services_meta_tags]
    meta_description = "Quality Support Coordination and Specialist Support Coordination"
    meta_og_title = "Topwise Support Services - What We Do!"
    meta_og_type = "website"
    meta_og_url = "https://www.topwisesupport.com.au/services/"
    meta_og_description = "Details on our services which allows us to provide the high quality support coordination"
    meta_twitter_card = "summary"
    meta_og_image = "images/Weblinklogo.webp"

  [params.contact_meta_tags]
    meta_description = "Reach Out to See How We Can Support You"
    meta_og_title = "Contact Topwise Support - Melbourne"
    meta_og_type = "website"
    meta_og_url = "https://www.topwisesupport.com.au/contact/"
    meta_og_description = "Melbourne Based Support Cordination Contact Details"
    meta_twitter_card = "summary"
    meta_og_image = "images/Weblinklogo.webp"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Our Services"
    url = "/services/"
    weight = 3

[[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
